services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}/app:${COMPOSE_STAGE}
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - sessions:/app/sessions

  nginx:
    image: ghcr.io/${GITHUB_REPOSITORY}/nginx:${COMPOSE_STAGE}
    restart: unless-stopped
    depends_on:
      - app
    expose:
      - 80
    ports:
      - ${COMPOSE_NGINX_PORT}:80

volumes:
  sessions:
    driver: local
